#!/usr/bin/env python3
"""Generate prioritized outreach list from CRM contacts."""
import json
import os

DIR = os.path.dirname(os.path.abspath(__file__))

def load(fn):
    p = os.path.join(DIR, fn)
    if os.path.exists(p):
        with open(p) as f:
            return json.load(f)
    return None

def score_contact(c):
    """Score a contact for outreach priority (higher = reach out first)."""
    score = 0
    
    # Relationship strength (most important)
    strength = c.get("relationship_strength", "weak")
    if strength == "strong":
        score += 40
    elif strength == "warm":
        score += 25
    
    # Number of matching jobs (more = more reason to reach out)
    mj = c.get("matching_jobs", 0)
    if isinstance(mj, list):
        mj_count = len(mj)
    else:
        mj_count = mj if isinstance(mj, int) else 0
    score += min(mj_count * 3, 30)  # cap at 30
    
    # Has actionable contact info
    if c.get("email"):
        score += 10
    if c.get("wechat"):
        score += 8
    if c.get("linkedin"):
        score += 5
    
    # Follow-up needed
    if c.get("follow_up_needed") == "true":
        score += 15
    
    # Company has applications (already engaged)
    if c.get("application_status") and c["application_status"] != "none":
        score += 12
    
    # High-grade jobs found
    grades = c.get("job_grades_found", [])
    if isinstance(grades, list):
        a_count = sum(1 for g in grades if g == "A")
        score += a_count * 5
    
    return score

def main():
    contacts = load("contacts.json") or []
    jobs = load("jobs-all.json") or []
    
    # Build company->jobs lookup
    company_jobs = {}
    for j in jobs:
        co = j.get("company", "")
        if co not in company_jobs:
            company_jobs[co] = []
        company_jobs[co].append(j)
    
    # Score and sort contacts
    scored = []
    for c in contacts:
        s = score_contact(c)
        c["_outreach_score"] = s
        scored.append(c)
    
    scored.sort(key=lambda c: c["_outreach_score"], reverse=True)
    
    # Generate markdown report
    lines = [
        "# 🎯 Outreach Priorities",
        "",
        f"*Auto-generated by crm-prioritize.py*",
        "",
        "Ranked by outreach value: relationship strength + matching jobs + contact availability.",
        "",
        "---",
        "",
        "## 🏆 Top 20 Contacts to Reach Out To",
        "",
    ]
    
    for i, c in enumerate(scored[:20], 1):
        mj = c.get("matching_jobs", 0)
        if isinstance(mj, list):
            mj_count = len(mj)
            top_jobs = [f"  - {j['title']} ({j.get('grade','?')})" for j in mj[:3]]
        else:
            mj_count = mj if isinstance(mj, int) else 0
            top_jobs = []
        
        strength_emoji = "💪" if c.get("relationship_strength") == "strong" else "🤝" if c.get("relationship_strength") == "warm" else "👤"
        contact_info = []
        if c.get("email"):
            contact_info.append(f"📧 {c['email']}")
        if c.get("wechat"):
            contact_info.append(f"💬 WeChat: {c['wechat']}")
        if c.get("linkedin"):
            contact_info.append(f"🔗 {c['linkedin']}")
        
        lines.append(f"### {i}. {c.get('name', 'Unknown')} @ {c.get('company', '?')}")
        lines.append(f"**Score:** {c['_outreach_score']} | **Strength:** {strength_emoji} {c.get('relationship_strength', 'unknown')} | **Matching Jobs:** {mj_count}")
        if c.get("title"):
            lines.append(f"**Role:** {c['title']}")
        if contact_info:
            lines.append(f"**Contact:** {' | '.join(contact_info)}")
        if top_jobs:
            lines.append("**Top matching roles:**")
            lines.extend(top_jobs)
        lines.append("")
    
    # Summary stats
    lines.extend([
        "---",
        "",
        "## 📊 Summary",
        "",
        f"- **Total contacts:** {len(scored)}",
        f"- **Strong relationships:** {sum(1 for c in scored if c.get('relationship_strength') == 'strong')}",
        f"- **Warm relationships:** {sum(1 for c in scored if c.get('relationship_strength') == 'warm')}",
        f"- **With email:** {sum(1 for c in scored if c.get('email'))}",
        f"- **With WeChat:** {sum(1 for c in scored if c.get('wechat'))}",
        f"- **With matching jobs:** {sum(1 for c in scored if isinstance(c.get('matching_jobs'), list) and len(c['matching_jobs']) > 0)}",
        "",
        "## 🎯 Suggested Actions",
        "",
        "1. **Strong + high score:** Personal message, reference specific roles",
        "2. **Warm + matching jobs:** Ask about company culture, get referral",
        "3. **Has email + jobs:** Cold outreach with tailored cover letter",
        "4. **WeChat available:** WeChat intro for Chinese companies",
    ])
    
    report = "\n".join(lines)
    
    # Write report
    report_path = os.path.join(DIR, "outreach-priorities.md")
    with open(report_path, "w") as f:
        f.write(report)
    
    print(f"✅ Outreach priorities generated: {report_path}")
    print(f"   Total contacts: {len(scored)}")
    print(f"   Top score: {scored[0]['_outreach_score']} ({scored[0]['name']})")
    print(f"   Strong: {sum(1 for c in scored if c.get('relationship_strength') == 'strong')}")

if __name__ == "__main__":
    main()
