#!/usr/bin/env python3
"""
Application Priority Engine — Career OS
Generates a prioritized weekly application plan from the jobs database.

Scoring factors:
1. Quality score (base)
2. Direct apply bonus (+5)
3. Easy difficulty bonus (+3), Hard penalty (-5)
4. English-friendly bonus (+2)
5. Top-20 flag bonus (+3)
6. City balance penalty (if >30% of week's apps are same city, -2)

Output: Prioritized job list + weekly application plan
"""

import json
import sys
from collections import Counter, defaultdict
from datetime import datetime, timedelta

def load_jobs(path):
    with open(path) as f:
        return json.load(f)

def compute_priority_score(job):
    """Compute application priority score (higher = apply first)."""
    base = job.get("quality_score", 0)
    
    # Direct apply bonus (much easier to actually apply)
    direct = 5 if job.get("has_direct_apply") else 0
    
    # Difficulty adjustment
    diff = job.get("app_difficulty", "medium")
    diff_map = {"easy": 3, "medium": 0, "hard": -5}
    diff_adj = diff_map.get(diff, 0)
    
    # English-friendly bonus
    en = 2 if job.get("english_friendly") else 0
    
    # Top-20 flag bonus
    top20 = 3 if job.get("top20") else 0
    
    # Category bonus (prioritize sweet spots)
    cat = job.get("category", "")
    cat_bonus = {"cross_border": 3, "fintech": 2, "strategy": 2, "ai_product": 1}.get(cat, 0)
    
    # City diversity (handled in plan generation, not here)
    
    return base + direct + diff_adj + en + top20 + cat_bonus

def generate_weekly_plan(jobs, week_start=None, max_per_day=4, max_per_week=20):
    """Generate a weekly application plan with city balance."""
    if week_start is None:
        # Next Monday
        today = datetime.now()
        days_until_monday = (7 - today.weekday()) % 7
        if days_until_monday == 0:
            days_until_monday = 7
        week_start = today + timedelta(days=days_until_monday)
    
    # Filter to English-friendly, not low quality, not applied
    eligible = [
        j for j in jobs
        if j.get("english_friendly", False)
        and not j.get("low_quality", False)
        and j.get("status") in ("not_applied", "unknown")
        and j.get("quality_score", 0) >= 70
    ]
    
    # Compute priority scores
    for j in eligible:
        j["_priority"] = compute_priority_score(j)
    
    # Sort by priority
    eligible.sort(key=lambda x: x["_priority"], reverse=True)
    
    # Build weekly plan with city balance
    plan = defaultdict(list)
    city_counts = Counter()
    day_names = ["Mon", "Tue", "Wed", "Thu", "Fri"]
    
    selected = []
    for j in eligible:
        city = j.get("location_norm", "Unknown")
        day_idx = len(selected) // max_per_day
        if day_idx >= 5:
            break
        
        # Check city balance: no more than 40% of any day in same city
        day_city_counts = Counter(s.get("location_norm") for s in plan[day_names[day_idx]])
        if day_city_counts[city] >= 3 and max_per_day > 3:
            continue
        
        selected.append(j)
        plan[day_names[day_idx]].append(j)
        city_counts[city] += 1
    
    return selected, plan, city_counts

def format_plan(plan, city_counts, week_start):
    """Format the weekly plan as markdown."""
    lines = []
    lines.append(f"# Weekly Application Plan — Week of {week_start.strftime('%B %d, %Y')}")
    lines.append("")
    lines.append("**Generated by:** Application Priority Engine")
    lines.append(f"**Total jobs to apply:** {sum(len(v) for v in plan.values())}")
    lines.append("")
    
    # City balance summary
    total = sum(city_counts.values())
    lines.append("## City Balance")
    lines.append("")
    for city, count in city_counts.most_common():
        pct = 100 * count / total if total > 0 else 0
        lines.append(f"- **{city}:** {count} ({pct:.0f}%)")
    lines.append("")
    
    # Daily plan
    lines.append("## Daily Plan")
    lines.append("")
    
    for day, jobs in plan.items():
        if not jobs:
            continue
        day_date = week_start + timedelta(days=["Mon","Tue","Wed","Thu","Fri"].index(day))
        lines.append(f"### {day} ({day_date.strftime('%b %d')}) — {len(jobs)} applications")
        lines.append("")
        lines.append("| Priority | Company | Role | City | Score | Difficulty | Direct Apply | Est. Time |")
        lines.append("|----------|---------|------|------|-------|------------|--------------|-----------|")
        
        for j in jobs:
            direct = "✅" if j.get("has_direct_apply") else "❌"
            diff = j.get("app_difficulty", "?")
            time_est = j.get("app_time_est", "?")
            score = j.get("quality_score", 0)
            top20 = " ⭐" if j.get("top20") else ""
            lines.append(f"| {j['_priority']} | {j.get('company', '?')} | {j.get('title', '?')[:50]}{top20} | {j.get('location_norm', '?')} | {score} | {diff} | {direct} | {time_est} |")
        
        lines.append("")
    
    # Tier breakdown
    lines.append("## Application Tier Breakdown")
    lines.append("")
    
    tier1 = [j for j in sum(plan.values(), []) if j.get("quality_score", 0) >= 90]
    tier2 = [j for j in sum(plan.values(), []) if 80 <= j.get("quality_score", 0) < 90]
    tier3 = [j for j in sum(plan.values(), []) if j.get("quality_score", 0) < 80]
    
    lines.append(f"- **Tier 1 (Score 90+):** {len(tier1)} roles — Apply first, highest leverage")
    lines.append(f"- **Tier 2 (Score 80-89):** {len(tier2)} roles — Apply mid-week, strong fit")
    lines.append(f"- **Tier 3 (Score 70-79):** {len(tier3)} roles — Apply end of week, volume play")
    lines.append("")
    
    # Strategy notes
    lines.append("## Strategy Notes")
    lines.append("")
    lines.append("1. **Easy wins first:** Direct-apply jobs (✅) should be done early in the day when energy is highest")
    lines.append("2. **Hard applications:** Jobs marked 'hard' may require cover letters or multi-step forms — batch these together")
    lines.append("3. **City balance:** Plan maintains geographic diversity to avoid over-indexing on one market")
    lines.append("4. **Referral prep:** For Tier 1 jobs without direct apply, prioritize getting referrals from contacts database")
    lines.append("5. **Time estimate:** Total estimated time per day is shown — adjust if running behind")
    lines.append("")
    
    # Time estimates
    all_jobs = sum(plan.values(), [])
    easy_time = sum(1 for j in all_jobs if j.get("app_difficulty") == "easy")
    med_time = sum(1 for j in all_jobs if j.get("app_difficulty") == "medium")
    hard_time = sum(1 for j in all_jobs if j.get("app_difficulty") == "hard")
    total_minutes = easy_time * 4 + med_time * 12 + hard_time * 25
    lines.append(f"## Time Investment")
    lines.append("")
    lines.append(f"- Easy applications: {easy_time} × ~4 min = {easy_time * 4} min")
    lines.append(f"- Medium applications: {med_time} × ~12 min = {med_time * 12} min")
    lines.append(f"- Hard applications: {hard_time} × ~25 min = {hard_time * 25} min")
    lines.append(f"- **Total estimated time:** {total_minutes} min ({total_minutes/60:.1f} hours)")
    lines.append("")
    
    return "\n".join(lines)

def main():
    jobs_path = "/Users/iancolrick/.openclaw/workspace/career-os/OKComputer_职位搜索清单/jobs-all.json"
    output_path = "/Users/iancolrick/.openclaw/workspace/career-os/strategy/weekly-application-plan.md"
    
    jobs = load_jobs(jobs_path)
    print(f"Loaded {len(jobs)} jobs")
    
    selected, plan, city_counts = generate_weekly_plan(jobs)
    print(f"Selected {len(selected)} jobs for this week")
    
    # Find next Monday
    today = datetime.now()
    days_until_monday = (7 - today.weekday()) % 7
    if days_until_monday == 0:
        days_until_monday = 7
    week_start = today + timedelta(days=days_until_monday)
    
    plan_md = format_plan(plan, city_counts, week_start)
    
    with open(output_path, "w") as f:
        f.write(plan_md)
    
    print(f"Plan written to {output_path}")
    print()
    
    # Print summary
    print("=== WEEKLY PLAN SUMMARY ===")
    for day, jobs in plan.items():
        if jobs:
            print(f"\n{day}: {len(jobs)} applications")
            for j in jobs[:3]:
                print(f"  [{j['_priority']}] {j.get('company')} - {j.get('title')[:45]} ({j.get('location_norm')})")
            if len(jobs) > 3:
                print(f"  ... and {len(jobs)-3} more")
    
    print(f"\nCity balance:")
    total = sum(city_counts.values())
    for city, count in city_counts.most_common():
        print(f"  {city}: {count} ({100*count/total:.0f}%)")

if __name__ == "__main__":
    main()
