#!/usr/bin/env python3
"""
Daily Job Recommendation Engine
Generates the daily briefing with top ~20 job recommendations.
"""
import json
import sys
from pathlib import Path
from datetime import datetime, timedelta

# Import the enhanced scorer
sys.path.insert(0, str(Path(__file__).parent))
from enhanced_scorer import get_location_priority

JOBS_PATH = Path('/Users/iancolrick/OKComputer_职位搜索清单/jobs-all.json')
OUTPUT_DIR = Path('/Users/iancolrick/.openclaw/workspace/job_recommender/daily_reports')


def load_jobs():
    """Load and validate jobs database."""
    with open(JOBS_PATH) as f:
        jobs = json.load(f)
    return jobs


def filter_eligible(jobs):
    """Filter to eligible, non-excluded, non-low-quality jobs."""
    eligible = []
    for j in jobs:
        if j.get('excluded'):
            continue
        if j.get('low_quality'):
            continue
        score = j.get('quality_score', 0)
        if score < 30:
            continue
        eligible.append(j)
    return eligible


def rank_jobs(jobs, top_n=20):
    """Rank jobs by composite score with tie-breaking."""
    for j in jobs:
        # Composite score: quality + location priority + freshness
        loc_priority = get_location_priority(j.get('location', ''))
        freshness = j.get('score_breakdown', {}).get('freshness', 0)
        j['_rank_score'] = (
            j.get('quality_score', 0) * 1000  # Primary: quality
            + freshness * 100                    # Secondary: freshness
            + (100 - loc_priority * 10)          # Tertiary: location preference
        )
    
    jobs.sort(key=lambda x: x['_rank_score'], reverse=True)
    return jobs[:top_n]


def generate_briefing(recommendations, jobs_stats):
    """Generate markdown briefing."""
    today = datetime.now().strftime('%Y-%m-%d')
    weekday = datetime.now().strftime('%A')
    
    lines = [
        f"# 📋 Daily Job Briefing — {weekday}, {today}",
        "",
        "## Summary",
        f"- **Total jobs in database:** {jobs_stats['total']}",
        f"- **Eligible (non-excluded, score ≥30):** {jobs_stats['eligible']}",
        f"- **Tier A (≥70):** {jobs_stats['tier_a']}",
        f"- **Tier B (50-69):** {jobs_stats['tier_b']}",
        f"- **Excluded (Amazon):** {jobs_stats['excluded']}",
        "",
        "## 🎯 Top 20 Recommendations",
        "",
    ]
    
    for i, job in enumerate(recommendations, 1):
        bd = job.get('score_breakdown', {})
        emoji = '🔴' if job.get('quality_tier') == 'A' else '🟡' if job.get('quality_tier') == 'B' else '🟢'
        
        lines.append(f"### {i}. {emoji} [{job['quality_score']}] {job['title']}")
        lines.append(f"- **Company:** {job.get('company_raw', 'N/A')}")
        lines.append(f"- **Location:** {job.get('location', 'N/A')}")
        lines.append(f"- **Tier:** {job.get('quality_tier', '?')}")
        lines.append(f"- **Score:** YOE:{bd.get('yoe_match',0):+d} | Salary:{bd.get('salary_match',0):+d} | Domain:{bd.get('domain_match',0):+d} | Location:{bd.get('location_match',0):+d} | English:{bd.get('english_match',0):+d}")
        
        if job.get('url'):
            lines.append(f"- **URL:** {job['url']}")
        
        if job.get('notes'):
            notes = job['notes'][:150]
            lines.append(f"- **Notes:** {notes}")
        
        lines.append(f"- **Action:** ⬜ Review | ⬜ Apply | ⬜ Skip")
        lines.append("")
    
    # Location breakdown
    lines.append("## 📍 Location Breakdown")
    from collections import Counter
    loc_counts = Counter(j.get('location', '?') for j in recommendations)
    for loc, count in sorted(loc_counts.items(), key=lambda x: -x[1]):
        lines.append(f"- {loc}: {count}")
    
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by Career OS Daily Recommender — {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
    
    return "\n".join(lines)


def main():
    """Run daily recommendation pipeline."""
    jobs = load_jobs()
    
    # Stats
    excluded = sum(1 for j in jobs if j.get('excluded'))
    eligible = filter_eligible(jobs)
    tier_a = sum(1 for j in eligible if j.get('quality_tier') == 'A')
    tier_b = sum(1 for j in eligible if j.get('quality_tier') == 'B')
    
    stats = {
        'total': len(jobs),
        'eligible': len(eligible),
        'tier_a': tier_a,
        'tier_b': tier_b,
        'excluded': excluded,
    }
    
    print(f"=== Daily Job Recommendations ===")
    print(f"Total: {stats['total']} | Eligible: {stats['eligible']} | A: {stats['tier_a']} | B: {stats['tier_b']} | Excluded: {stats['excluded']}")
    
    # Rank and get top 20
    recommendations = rank_jobs(eligible, top_n=20)
    
    # Generate briefing
    briefing = generate_briefing(recommendations, stats)
    
    # Save briefing
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    today = datetime.now().strftime('%Y-%m-%d')
    briefing_path = OUTPUT_DIR / f'briefing-{today}.md'
    with open(briefing_path, 'w') as f:
        f.write(briefing)
    
    print(f"\nBriefing saved: {briefing_path}")
    
    # Save recommendations as JSON for sheets sync
    recs_path = OUTPUT_DIR / f'recommendations-{today}.json'
    with open(recs_path, 'w') as f:
        json.dump(recommendations, f, ensure_ascii=False, indent=2)
    
    # Print summary
    print(f"\n=== Today's Top 5 ===")
    for i, job in enumerate(recommendations[:5], 1):
        print(f"{i}. [{job['quality_score']}] {job['title']} @ {job.get('company_raw', '?')} [{job.get('location', '?')}]")
    
    return recommendations, stats, briefing


if __name__ == '__main__':
    main()
